modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/ThinkingStudios/CITFoxified/issues"

[[mods]]
modId = "citfoxified"
version = "${mod_version}"
displayName = "CITFoxified"
displayURL="https://github.com/ThinkingStudios/CITFoxified" #optional
logoFile="icon.png" #optional
credits="SHsuperCM" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
CITResewn unofficial (Neo)Forge port.

Re-implements MCPatcher's CIT
'''

[[mixins]]
config = "citresewn.mixins.json"

[[dependencies.citfoxified]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.citfoxified]]
modId = "minecraft"
type = "required"
versionRange = "${mod_target_mc}"
ordering = "NONE"
side = "BOTH"

[[dependencies.citfoxified]]
modId = "cloth_config"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"